# Generated by Django 3.0.5 on 2020-04-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=12)),
                ('attrs_str', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attrs_dex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attrs_con', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attrs_int', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attrs_wis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attrs_cha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('race', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('alignment', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=12)),
                ('background', models.CharField(max_length=10)),
                ('bonds', models.CharField(max_length=50)),
                ('ideals', models.CharField(max_length=50)),
                ('flaws', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
