# Generated by Django 3.0.5 on 2020-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_charsheet_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charsheet',
            name='attrs_str',
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='background',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='bonds',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='flaws',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='ideals',
            field=models.TextField(max_length=300),
        ),
    ]
