# Generated by Django 3.0.5 on 2020-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20200504_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='charsheet',
            name='attrs_str',
            field=models.IntegerField(default=10),
        ),
    ]
