# Generated by Django 3.0.5 on 2020-05-04 16:05

from django.db import migrations, models
import journal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_charsheet_attrs_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_str',
            field=models.IntegerField(default=10, validators=[journal.validators.validate_attrs]),
        ),
    ]
