# Generated by Django 3.0.5 on 2020-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20200504_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_str',
            field=models.IntegerField(default=10),
        ),
    ]
