# Generated by Django 3.0.5 on 2020-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20200504_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_cha',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_con',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_dex',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_int',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='attrs_wis',
            field=models.IntegerField(default=10),
        ),
    ]
