# Generated by Django 3.0.5 on 2020-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20200504_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='charsheet',
            name='description',
            field=models.TextField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='charsheet',
            name='spell',
            field=models.TextField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='charsheet',
            name='weapon',
            field=models.TextField(max_length=12, null=True),
        ),
    ]
