# Generated by Django 3.0.5 on 2020-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20200507_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='spell',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='weapon',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
